name: Build Check Workflow

on:
  workflow_run:
    workflows: [Code Lint Workflow]
    types:
      - requested

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkouts@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the project dependencies
        run: npm install

      - name: Build the project
        run: npm run build


