name: code check workflow


on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '25 21 * * 5'

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the project dependencies
        run: npm install

      - name: fix code style issues with prettier & eslint
        run: npm run lint:fix && npm run prettier:fix

      - name: Build the project
        run: npm run build

      - name: Prettier check
        run: npm run prettier

      - name: Lint check
        run: npm run lint

      - name: TS check
        run: npm run tsc
