name: code check workflow


on:
  push:
    branches:
      - [dm][ea][vi]*
  pull_request:
    types:
      - opened
  schedule:
    - cron: '25 21 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install the project dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Prettier check
        run: npm run prettier

      - name: Lint check
        run: npm run lint

      - name: TS check
        run: npm run tsc
