name: Code Lint Workflow

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install the project dependencies
        run: npm install

      - name: Fix code style issues with prettier & eslint
        run: npm run lint:fix && npm run prettier:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling